# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\fyb\Desktop\yolov5\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1960, 1340)
        self.label_ori = QtWidgets.QLabel(Dialog)
        self.label_ori.setGeometry(QtCore.QRect(40, 120, 900, 900))
        self.label_ori.setFrameShape(QtWidgets.QFrame.Box)
        self.label_ori.setLineWidth(1)
        self.label_ori.setMidLineWidth(0)
        self.label_ori.setText("")
        self.label_ori.setObjectName("label_ori")
        self.label_det = QtWidgets.QLabel(Dialog)
        self.label_det.setGeometry(QtCore.QRect(1020, 120, 900, 900))
        self.label_det.setFrameShape(QtWidgets.QFrame.Box)
        self.label_det.setText("")
        self.label_det.setObjectName("label_det")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(40, 1050, 1881, 250))
        self.textBrowser.setObjectName("textBrowser")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 1901, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Model = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Model.setFont(font)
        self.pushButton_Model.setObjectName("pushButton_Model")
        self.horizontalLayout.addWidget(self.pushButton_Model)
        self.pushButton_Img = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Img.setFont(font)
        self.pushButton_Img.setObjectName("pushButton_Img")
        self.horizontalLayout.addWidget(self.pushButton_Img)
        self.pushButton_ImgFolder = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_ImgFolder.setFont(font)
        self.pushButton_ImgFolder.setObjectName("pushButton_ImgFolder")
        self.horizontalLayout.addWidget(self.pushButton_ImgFolder)
        self.pushButton_Video = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Video.setFont(font)
        self.pushButton_Video.setObjectName("pushButton_Video")
        self.horizontalLayout.addWidget(self.pushButton_Video)
        self.pushButton_Camera = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Camera.setFont(font)
        self.pushButton_Camera.setObjectName("pushButton_Camera")
        self.horizontalLayout.addWidget(self.pushButton_Camera)
        self.pushButton_BegDet = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_BegDet.setFont(font)
        self.pushButton_BegDet.setObjectName("pushButton_BegDet")
        self.horizontalLayout.addWidget(self.pushButton_BegDet)
        self.pushButton_StopDet = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_StopDet.setFont(font)
        self.pushButton_StopDet.setObjectName("pushButton_StopDet")
        self.horizontalLayout.addWidget(self.pushButton_StopDet)
        self.pushButton_SavePath = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_SavePath.setFont(font)
        self.pushButton_SavePath.setObjectName("pushButton_SavePath")
        self.horizontalLayout.addWidget(self.pushButton_SavePath)
        self.pushButton_Exit = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_Exit.setFont(font)
        self.pushButton_Exit.setObjectName("pushButton_Exit")
        self.horizontalLayout.addWidget(self.pushButton_Exit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "蔬果检测器v1"))
        self.pushButton_Model.setText(_translate("Dialog", "选择配置文件"))
        self.pushButton_Img.setText(_translate("Dialog", "打开图片"))
        self.pushButton_ImgFolder.setText(_translate("Dialog", "打开文件夹"))
        self.pushButton_Video.setText(_translate("Dialog", "打开视频"))
        self.pushButton_Camera.setText(_translate("Dialog", "打开摄像头"))
        self.pushButton_BegDet.setText(_translate("Dialog", "开始检测"))
        self.pushButton_StopDet.setText(_translate("Dialog", "停止检测"))
        self.pushButton_SavePath.setText(_translate("Dialog", "设置保存路径"))
        self.pushButton_Exit.setText(_translate("Dialog", "退出"))

